name: Check for broken links on site

on:
  workflow_dispatch:

jobs:
  check-links-on-site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4
      - name: Link Checker 🔗
        uses: lycheeverse/lychee-action@v1.9.0
        with:
          fail: true
          args: --offline --verbose --no-progress 'site/**/*.html'
